// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEy-qfpEIInbnfr1EIB8rb-2dNv2O0a0o',
    appId: '1:710512977280:web:94bc0c441aa9d345b04d65',
    messagingSenderId: '710512977280',
    projectId: 'zerokoin-705c5',
    authDomain: 'zerokoin-705c5.firebaseapp.com',
    storageBucket: 'zerokoin-705c5.firebasestorage.app',
    measurementId: 'G-R1CQYYB731',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO744IB8qAI9o3pGz3dMd_rtR7m4_WYVQ',
    appId: '1:710512977280:android:abb8b239ba4bf871b04d65',
    messagingSenderId: '710512977280',
    projectId: 'zerokoin-705c5',
    storageBucket: 'zerokoin-705c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX-Wikuj10Ywnx7Z7uMjf4q7xyJymyL2U',
    appId: '1:710512977280:ios:1f3c5865fdfaf88cb04d65',
    messagingSenderId: '710512977280',
    projectId: 'zerokoin-705c5',
    storageBucket: 'zerokoin-705c5.firebasestorage.app',
    androidClientId: '710512977280-5ectqdoorq1saljvd6l7o4f8gvr75j8n.apps.googleusercontent.com',
    iosClientId: '710512977280-4up130t8dmipj0smtfalmkf4526adrkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.zeroKoin',
  );
}
